/* auto-generated by NAPI-RS */
/* eslint-disable */

/**
 * Which binding artifact the generated loader actually loaded: `'native'` for
 * a native addon, otherwise the `platformArchABI` of the WASI flavor. Every
 * flavor napi-rs can build is listed, because `NAPI_RS_NATIVE_LIBRARY_PATH`
 * can point the loader at a WASI artifact this package does not build itself.
 */
export declare const __napiBindingTarget: 'native' | 'wasm32-wasi' | 'wasm32-wasip1'

/** kind 0: a space-separated Tailwind class string; kind 1: a CSS property and value. */
export interface Candidate {
  kind: number
  text: string
}

export interface Finding {
  index: number
  value: string
  group: number
}

export declare function scan(candidates: Array<Candidate>): Array<Finding>
